name: Update OMI's official Google Sheets spreadsheet.

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update_gs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'

      - name: "Install uv"
        uses: astral-sh/setup-uv@v7

      - name: "Install dependencies"
        run: uv sync

      - name: "Copy service account"
        env:
          SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: |
          mkdir -p $HOME/.config/gspread/
          echo "$SERVICE_ACCOUNT" > ~/.config/gspread/service_account.json

      - name: "Update sheet"
        env:
          GS_SHEET_KEY: ${{ secrets.GS_SHEET_KEY }}
        run: |
          uv run python3 main.py
